services:
  qdrant:
    image: qdrant/qdrant:v1.11.0
    ports:
      - "6333:6333"
    environment:
      QDRANT__SERVICE__ENABLE_CORS: "true"
    volumes:
      - qdrant_data:/qdrant/storage

  api:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.api
    env_file: .env
    environment:
      - QDRANT_URL=${QDRANT_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-info}
    volumes:
      - ./src:/app/src
    ports:
      - "${API_PORT:-8000}:8000"
    depends_on:
      - qdrant

  web:
    build:
      context: .
      dockerfile: infra/docker/Dockerfile.web
    env_file: .env
    environment:
      - NEXT_PUBLIC_API_BASE=${NEXT_PUBLIC_API_BASE}
    volumes:
      - ./apps/web:/app
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  qdrant_data:
