name: Preview (stub)

on:
  pull_request:

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Preview stub
        run: echo "Spin up ephemeral preview on your platform (Render/Fly/Heroku)"
