name: Preview (stub)
on:
  pull_request:
    paths:
      - 'apps/web/**'
      - 'infra/**'
      - '.github/workflows/preview.yml'
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo "Preview for web/infra changes"
